### PR TITLE
Weight Programming Optimization Feature Addition

### PR DESCRIPTION
**Pull request by charlesmackin**
## Description

Adapted and improved weight programming optimization feature from rpusim as described in "Optimised weight programming for analogue memory-based deep neural networks," _Nature Communications_ 2022.

## Details

Weight programming optimization is completely contained in an independent file: src/aihwkit/inference/converter/wpo.py

It works by realizing that different weight values can be split in different ways across n-pairs of conductances such a way that you can minimize weight programming, drift, and read noise associated errors.  Optimization occurs using differential evolution on an AnalogLinear tile with weights that are representative of the network weights. In this way, we make use of the all the rpu_config device non-idealities as well as other parameters contained within the tile such as the drift compensation technique. The process returns an optimized CustomConductancePairConverter, which can be used to replace the standard g_converter and improve network accuracy.

I have also included an example: 33_weight_programming_optimization.py to illustrate the feature. This example optimizes programming on the bert on squad network described in a previous example. It plots the baseline versus optimized programming strategies along with the subsequent improvement in weight errors and output activations. Lastly, it shows that accuracy can be improved as well.

I also included tests for the weight programming optimization. Input parameters were greatly simplified in order to make each test as fast as possible.  Normally the differential evolution process is quite time consuming, which can be prohibitive for tests.

### CODE REVIEW

**Comment by PabloCarmona** [comment]
Nice addition @charlesmackin! Do you think that could be good or make sense to add a section of documentation that showcase and explains this new capability?

**Comment by PabloCarmona** [comment]
@charlesmackin I'm trying to run the example you created and this is the output of it. Let me know if the results are ok and the error seems to be because I'm running this in a macOS M1 Pro laptop or is other thing?

```bash
python examples/33_weight_programming_optimization.py 
Matplotlib is building the font cache; this may take a moment.
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████| 48.0/48.0 [00:00<00:00, 67.4kB/s]
config.json: 100%|████████████████████████████████████████████████████████████████████████| 477/477 [00:00<00:00, 1.47MB/s]
vocab.txt: 100%|████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 5.33MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 95.7kB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████| 438M/438M [00:09<00:00, 44.6MB/s]
Some weights of the model checkpoint at csarron/bert-base-uncased-squad-v1 were not used when initializing BertForQuestionAnswering: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

	loss baseline = 0.101346 (DualPairConductanceConverter)

		hypercube dimensions = 19 

	(current loss - baseline loss) / baseline loss + loss margin = 1.0766843337 (2024-12-20 12:45:54.034749)
	(current loss - baseline loss) / baseline loss + loss margin = 0.8149927889 (2024-12-20 12:46:23.673485)
	(current loss - baseline loss) / baseline loss + loss margin = 0.6739507360 (2024-12-20 12:46:54.425789)
	(current loss - baseline loss) / baseline loss + loss margin = 0.5452067969 (2024-12-20 12:47:27.398618)
	(current loss - baseline loss) / baseline loss + loss margin = 0.5345655953 (2024-12-20 12:47:58.751386)
	(current loss - baseline loss) / baseline loss + loss margin = 0.4297244036 (2024-12-20 12:48:29.805743)
	(current loss - baseline loss) / baseline loss + loss margin = 0.3014009781 (2024-12-20 12:49:00.180243)
	(current loss - baseline loss) / baseline loss + loss margin = 0.3014009781 (2024-12-20 12:49:30.724303)
	(current loss - baseline loss) / baseline loss + loss margin = 0.2446655958 (2024-12-20 12:50:00.777138)
	(current loss - baseline loss) / baseline loss + loss margin = 0.2354773718 (2024-12-20 12:50:31.355769)
	(current loss - baseline loss) / baseline loss + loss margin = 0.1971104241 (2024-12-20 12:51:01.381043)
	(current loss - baseline loss) / baseline loss + loss margin = 0.1772974662 (2024-12-20 12:51:31.703327)
	(current loss - baseline loss) / baseline loss + loss margin = 0.1643101364 (2024-12-20 12:52:02.353588)
	(current loss - baseline loss) / baseline loss + loss margin = 0.1286772627 (2024-12-20 12:52:32.878338)
	(current loss - baseline loss) / baseline loss + loss margin = 0.1085523014 (2024-12-20 12:53:03.439664)
	(current loss - baseline loss) / baseline loss + loss margin = 0.1085523014 (2024-12-20 12:53:34.123273)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0940152464 (2024-12-20 12:54:04.573454)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0842283051 (2024-12-20 12:54:35.314870)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0725215571 (2024-12-20 12:55:05.572351)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0646350876 (2024-12-20 12:55:36.082212)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0525577436 (2024-12-20 12:56:06.551833)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0422969157 (2024-12-20 12:56:38.459008)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0380164981 (2024-12-20 12:57:09.622706)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0380164981 (2024-12-20 12:57:40.144445)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0368180341 (2024-12-20 12:58:10.376049)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 12:58:40.986238)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 12:59:11.077307)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 12:59:42.031922)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 13:00:13.238383)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 13:00:43.799569)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 13:01:13.743551)
	(current loss - baseline loss) / baseline loss + loss margin = 0.0306158985 (2024-12-20 13:01:43.769214)
Successful convergence: 0.03061589845188628
Plotting weight dispersion comparison over time: 33_results/m0.1_r0.3_kw1_lm0.2/DualPairConductanceConverter_comparison.png
Plotting z dispersion comparison over time: 33_results/m0.1_r0.3_kw1_lm0.2/DualPairConductanceConverter_comparison.png
Creating dataset.
README.md: 100%|██████████████████████████████████████████████████████████████████████| 7.62k/7.62k [00:00<00:00, 14.7MB/s]
train-00000-of-00001.parquet: 100%|███████████████████████████████████████████████████| 14.5M/14.5M [00:00<00:00, 40.6MB/s]
validation-00000-of-00001.parquet: 100%|██████████████████████████████████████████████| 1.82M/1.82M [00:00<00:00, 18.7MB/s]
Generating train split: 100%|████████████████████████████████████████████| 87599/87599 [00:00<00:00, 1210547.28 examples/s]
Generating validation split: 100%|███████████████████████████████████████| 10570/10570 [00:00<00:00, 1748040.11 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 10570/10570 [00:02<00:00, 5018.58 examples/s]
Evaluating model with baseline weight programming.
/Users/pxg/work/github.com/aihwkit/examples/33_weight_programming_optimization.py:758: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Downloading builder script: 100%|█████████████████████████████████████████████████████| 4.53k/4.53k [00:00<00:00, 23.7MB/s]
Downloading extra modules: 100%|██████████████████████████████████████████████████████| 3.32k/3.32k [00:00<00:00, 6.91MB/s]
Traceback (most recent call last):
  File "/Users/pxg/work/github.com/aihwkit/examples/33_weight_programming_optimization.py", line 1090, in <module>
    main()
  File "/Users/pxg/work/github.com/aihwkit/examples/33_weight_programming_optimization.py", line 1038, in main
    accuracy_baseline = do_inference(model_baseline, trainer_baseline,
  File "/Users/pxg/work/github.com/aihwkit/examples/33_weight_programming_optimization.py", line 795, in do_inference
    f1, exact_match = predict()
  File "/Users/pxg/work/github.com/aihwkit/examples/33_weight_programming_optimization.py", line 777, in predict
    raw_predictions = trainer.predict(eval_data)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/trainer.py", line 4128, in predict
    output = eval_loop(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/trainer.py", line 4244, in evaluation_loop
    losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/trainer.py", line 4470, in prediction_step
    outputs = model(**inputs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1947, in forward
    outputs = self.bert(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1142, in forward
    encoder_outputs = self.encoder(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    self_attention_outputs = self.attention(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 515, in forward
    self_outputs = self.self(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 395, in forward
    query_layer = self.transpose_for_scores(self.query(hidden_states))
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/.local/lib/python3.10/site-packages/aihwkit-0.9.2-py3.10-macosx-15.0-arm64.egg/aihwkit/nn/modules/linear.py", line 91, in forward
    return self.analog_module(x_input)  # type: ignore
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/.local/lib/python3.10/site-packages/aihwkit-0.9.2-py3.10-macosx-15.0-arm64.egg/aihwkit/simulator/tiles/array.py", line 162, in forward
    out_result.append(analog_tile(x, tensor_view=tensor_view))
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/pxg/.local/lib/python3.10/site-packages/aihwkit-0.9.2-py3.10-macosx-15.0-arm64.egg/aihwkit/simulator/tiles/inference.py", line 377, in forward
    out = AnalogFunction.apply(
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/pxg/.local/lib/python3.10/site-packages/aihwkit-0.9.2-py3.10-macosx-15.0-arm64.egg/aihwkit/simulator/tiles/functions.py", line 45, in forward
    analog_tile.ensure_shared_weights(shared_weights)
  File "/Users/pxg/miniconda3/envs/charlesmackin/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/pxg/.local/lib/python3.10/site-packages/aihwkit-0.9.2-py3.10-macosx-15.0-arm64.egg/aihwkit/simulator/tiles/rpucuda.py", line 185, in ensure_shared_weights
    self.tile.set_shared_weights(self.shared_weights.data)  # type: ignore
RuntimeError: weights must be a CPU tensor
python(24159,0x200b44240) malloc: Incorrect checksum for freed object 0x15a53bc10: probably modified after being freed.
Corrupt value: 0x7c369d7500000000
python(24159,0x200b44240) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python examples/33_weight_programming_optimization.py
```

Alongside with this I will add the snapshots for the results if serve of any help to reference the results and see if everything looks good:

bert_weight_distribution
device_models
DualPairConductanceConverter_vs_CustomPairConductanceConverter_bert
DualPairConductanceConverter_w_comparison_bert
DualPairConductanceConverter_w_error_comparison_bert
DualPairConductanceConverter_z_comparison_bert
DualPairConductanceConverter_z_error_comparison_bert

**Review by jubueche — APPROVED** [review]

**Comment by charlesmackin** [comment]
@PabloCarmona thanks for taking the time to run the example. I am unable to reproduce the error you list on your end. Can you try to troubleshoot the source of this cpu error? If you set the --optimize argument to 0 (false) since you've already completed that step, it will load the previous weight programming optimization result and proceed directly to the inference analysis. The final plot should look something like this: 
accuracy_comparison_bert

Otherwise, everything looks great. Thank you.

**Comment by charlesmackin** [comment]
@PabloCarmona I also submitted a new PR with descriptions added to the examples/README.md file for the new examples (31, 32, and 33) as requested. I think it's ok for now not to include detailed documentation on these new features as they should be mostly self explanatory from the examples and the cited paper. Thank you.

**Pull request merged**
