### PR TITLE
Changelog edits

### PR DESCRIPTION
**Pull request by maljoras**
## Description

Small edits correcting the changelog

### CODE REVIEW

**Review by kaoutar55 — CHANGES_REQUESTED** [review]
Hi @maljoras the notebooks are currently local to the aihwkit public repo and I removed the dependency on the other github repo.

**Comment by maljoras** [comment]
@kaoutar55 These are just small edits to the change logs here for consistency. Please check the files changed.

**Comment by maljoras** [comment]
@kaoutar55 I just change the order of the entry, I did not change anything from the earlier version. Are you saying they are not correct and I should remove the link?

**Comment by kaoutar55** [comment]
Hi Malte, we no longer depend on the other github repo for notebooks. They are all included within the current repo.

**Comment by maljoras** [comment]
@kaoutar55 I have not changed anything, that is what you wrote earlier, when you added the notebooks. I just corrected  the order. Please correct the content accordingly.

**Comment by kaoutar55** [comment]
Will do thanks!

**Comment by maljoras** [comment]
@kaoutar55 
I removed the link

**Review by kaoutar55 — APPROVED** [review]

**Pull request merged**
