### PR TITLE
Jart synapse

### PR DESCRIPTION
**Pull request by maljoras**
## Description

Support a new device type based on JART V1b memristor model and test scripts for that.
Details can be found at https://ieeexplore.ieee.org/document/10052010

## Details
The code was written for the old backend and some adaptations for the new version are needed.
Support for CUDA is strange, where sometimes the results are not transferred back to PyTorch.
Cycle-to-cycle variability is currently not supported for CUDA, as we need fields to save more device-specific parameters.

### CODE REVIEW

**Comment by maljoras** [comment]
@ZhenmingYu  I tried to change it but I think there are still a number of issues how the synapse is simulated. The logic to add the cycle-to-cycle noise is not correct. The cycle-to-cycle noise should be computed before updating the model as far as I can see, however, for instance the "ratio" parameter is always zero which cannot be correct.

**Comment by ZhenmingYu** [comment]
> @ZhenmingYu I tried to change it but I think there are still a number of issues how the synapse is simulated. The logic to add the cycle-to-cycle noise is not correct. The cycle-to-cycle noise should be computed before updating the model as far as I can see, however, for instance the "ratio" parameter is always zero which cannot be correct.

@maljoras Thanks for the checking the code.
I just came back from vacation and started looking at this.

You are right that "ratio" is 0 at most times, it was carried from the original model, fitted mostly with data collected in IV sweeps, and the purpose of this parameter is to scale the c2c noise with the update. If the update is large, then the filament area is disrupted heavily, which means that the c2c noise will be large. If the update is small, you are not quite changing the conductive filament, and the c2c noise will be 0.

However, in our use case, the update is small most of the time, so you will observe "ratio" parameter is mostly close to 0, and will render c2c noise useless, as shown in 
[https://ieeexplore.ieee.org/document/10052010](https://github.com/IBM/aihwkit/files/13952593/ASILOMAR_2022_Integration_of_physics_derived_memristor_models_with_machine_learning_frameworks.8.pdf) Figure 3 (f) and (g), the multiplicative noise (i.e.) scaled by "ratio" has no impact on the network performance.

**Comment by ZhenmingYu** [comment]
@maljoras I am also a bit lost in how should we bring this project forward, and your advice on this would be very appreciated.

I see that you are trying to simplify the computation by directly applying noise on dNdt. While this will work, it is not so much physically accurate anymore, which is where the JART model reeally shines.

On the other hand, In the past month I have been experimenting with a new [mathmatically fit of the model](https://ieeexplore.ieee.org/abstract/document/10192107), which will include read noise and make everything more accurate. However, it will include even more global parameters that will futher drag down the already too slow cuda initilization step.

Should we just drop the CUDA version instead?

**Review by kaoutar55 — APPROVED** [review]

**Comment by kaoutar55** [comment]
@ZhenmingYu and @maljoras, there are build errors. Can you take a look.

**Comment by maljoras** [comment]
Hi @kaoutar55, this PR is still WIP there are a number of issues still.

**Comment by Borjagodoy** [comment]
Hi @ZhenmingYu We are very interested in adding this new device that you propose, we would like to know if we can help you in any way or if you are still interested in this development :)

**Comment by ZhenmingYu** [comment]
> Hi @ZhenmingYu We are very interested in adding this new device that you propose, we would like to know if we can help you in any way or if you are still interested in this development :)

Hi @Borjagodoy

I had some bugs remaining there with the CUDA version, and the results that came out of that were not consistent with the CPU version.
However, on top of that, the CUDA version needed to copy a lot of parameters into GPU RAM, which resulted in a very long initialization time.
For a 3-layer ANN solving MNIST, the initialization time alone was much longer than the whole run on the CPU version.
So in the end I did all my tests with the CPU version, and I'm not sure whether it is worth it to invest more time and try to solve the bugs in the CUDA, or if would it be better to just cancel the support for the CUDA version.

**Comment by Borjagodoy** [comment]
It sounds reasonable, that if the initialisation time is longer than the execution time and shows no apparent improvement over CPU, we can document this and we should focus only on CPU support and cancel CUDA support, what do you think @kaoutar55 , @anu-pub?

**Comment by Borjagodoy** [comment]
hi @ZhenmingYu  we was talking about this PR and we are agree with only support the device only for CPU :) could you help to close this pr reviewing that the build works fine please?

**Comment by ZhenmingYu** [comment]
Hi @Borjagodoy 

I don't have permission to push to [maljoras/aihwkit](maljoras:jart-synapse), may I be added as a collaborator?

I think I fixed rpu_JART_v1b_device.h locally, and I think @maljoras was trying to make some simplification on the logic?
I will look into rpu_JART_v1b_device.cpp more tomorrow.

**Comment by ZhenmingYu** [comment]
@Borjagodoy 
The code is pushed to https://github.com/PGI15/aihwkit
I think I did everything correctly, and the CPU version is able to build now.
I will do more testing next week before I make another PR.

However, the CUDA side seems to have some unrelated problem?
Are you able to build it in your setup?

[  1%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_JART_v1b_device.cpp.o
[  2%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_buffered_transfer_device.cpp.o
[  3%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_chopped_transfer_device.cpp.o
[  5%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_constantstep_device.cpp.o
[  6%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_dynamic_transfer_device.cpp.o
[  7%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_expstep_device.cpp.o
[  8%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_forward_backward_pass.cpp.o
[ 10%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_hidden_device.cpp.o
[ 11%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_linearstep_device.cpp.o
[ 12%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_mixedprec_device.cpp.o
[ 13%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_mixedprec_device_base.cpp.o
[ 15%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_mixedprec_int_device.cpp.o
[ 16%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_onesided_device.cpp.o
[ 17%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_piecewisestep_device.cpp.o
[ 18%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_powstep_device.cpp.o
[ 20%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_powstep_reference_device.cpp.o
[ 21%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_pulsed.cpp.o
[ 22%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_pulsed_device.cpp.o
[ 23%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_pulsed_meta_parameter.cpp.o
[ 25%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_simple_device.cpp.o
[ 26%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_softbounds_reference_device.cpp.o
[ 27%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_transfer_device.cpp.o
[ 28%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_vector_device.cpp.o
[ 30%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/rpu_weight_updater.cpp.o
[ 31%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/sparse_bit_line_maker.cpp.o
[ 32%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/utility_functions.cpp.o
[ 33%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/weight_clipper.cpp.o
[ 35%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/weight_drifter.cpp.o
[ 36%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/weight_modifier.cpp.o
[ 37%] Building CXX object CMakeFiles/RPU_CPU.dir/src/rpucuda/weight_remapper.cpp.o
[ 38%] Linking CXX static library libRPU_CPU.a
[ 43%] Built target RPU_CPU
[ 45%] Building CUDA object CMakeFiles/RPU_GPU.dir/src/rpucuda/cuda/bit_line_maker.cu.o
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/RPU_GPU.dir/build.make:77: CMakeFiles/RPU_GPU.dir/src/rpucuda/cuda/bit_line_maker.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/RPU_GPU.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/Users/zyu/virtual_env/aihwkit/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 672, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/Users/zyu/virtual_env/aihwkit/lib/python3.10/site-packages/skbuild/cmaker.py", line 696, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/Users/zyu/virtual_env/aihwkit/lib/python3.10/site-packages/skbuild/cmaker.py", line 741, in make_impl
    raise SKBuildError(msg)

An error occurred while building with CMake.
  Command:
    /Users/zyu/virtual_env/aihwkit/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /Users/zyu/aihwkit
  Working directory:
    /Users/zyu/aihwkit/_skbuild/linux-x86_64-3.10/cmake-build
Please check the install target is valid and see CMake's output for more information.

**Comment by Borjagodoy** [comment]
close releted https://github.com/IBM/aihwkit/pull/679

**Pull request closed without merging**
